import hre from "hardhat";
import { getContract, getAddress, Address, encodeFunctionData, Hash } from "viem";
const poolAddresses = require("./pools.json");

const pools = {
  "ETH.ARB/ETH.ETH" : getAddress("0x6F29cc3d37e097E139318Da57CcD94e0C6BdE651"),
  "ETH.BASE/ETH.ETH" : getAddress("0xa02ce6b46a5292407109590711944156acb603ed"),
  "USDC.ETH/USDC.SOL" : getAddress("0x4e34C2d19dfcd8D0C0A275C38e641ca70ecC07B0"),
  "USDC.ETH/USDC.AVAX" : getAddress("0xBC2Ad0A8C8Db917C5677adB5bFe86a6bdA26f881"),
  "USDC.ARB/USDC.ETH" : getAddress("0xB54A28fb08527D9351EFBcE232AA46A245eED648"),
  "USDC.ETH/USDT.BSC" : getAddress("0xaa498BC13Da5858276B69911ddad4Afab1a6E579"),
  "USDC.BSC/USDC.ETH" : getAddress("0xF9C8550AaF70C3B4D3aE220f8137d60017944388"),
  "USDT.ARB/USDC.ETH" : getAddress("0x34dcE67748d0825225419206BfbbaA1A7d46D255"),
  "USDC.ETH/USDC.POL" : getAddress("0x9AB940C9BC41c3b4fBD0DdcCF19381142D2Ab134"),
  "USDC.ETH/USDT.POL" : getAddress("0x51cd2f04802F5Dc2Ec90Ae4A069B80D9647B3941"),
  "USDC.BSC/USDT.ETH" : getAddress("0x1576cd3540fa16208b8904ae402eb1fc08d27907"),
  "USDC.ETH/USDT.AVAX": getAddress("0x0e14aF42125772C05E4430d6FD6A140dA0818cAe"),
}

async function main() {
  const [walletClient] = await hre.viem.getWalletClients();
  const publicClient = await hre.viem.getPublicClient();

  const targetBaseFee = 100; // 0.01%
  for (const [pair, poolAddress] of Object.entries(pools)) {
    console.log(`Processing ${pair}`)
    const pool = getContract({
      address: getAddress(poolAddress),
      abi: ABI_AlgebraPool,
      client: { public: publicClient, wallet: walletClient },
    });
    const pluginAddr = await pool.read.plugin()
    const plugin = getContract({
      address: getAddress(pluginAddr),
      abi: ABI_AlgebraBasePluginV1,
      client: { public: publicClient, wallet: walletClient },
    })
    const [alpha1, alpha2, beta1, beta2, gamma1, gamma2, baseFee] = await plugin.read.feeConfig()
    if (targetBaseFee != baseFee) {
      const hash = await plugin.write.changeFeeConfiguration([{
        alpha1,
        alpha2,
        beta1,
        beta2,
        gamma1,
        gamma2,
        baseFee: targetBaseFee,
      }]);
      console.log("txHash", hash);
      await publicClient.waitForTransactionReceipt({ hash });
    }
  }
}

const ABI_AlgebraPool = [
  { inputs: [], name: "alreadyInitialized", type: "error" },
  { inputs: [], name: "arithmeticError", type: "error" },
  { inputs: [], name: "bottomTickLowerThanMIN", type: "error" },
  { inputs: [], name: "dynamicFeeActive", type: "error" },
  { inputs: [], name: "dynamicFeeDisabled", type: "error" },
  { inputs: [], name: "flashInsufficientPaid0", type: "error" },
  { inputs: [], name: "flashInsufficientPaid1", type: "error" },
  { inputs: [], name: "insufficientInputAmount", type: "error" },
  { inputs: [], name: "invalidAmountRequired", type: "error" },
  { inputs: [{ internalType: "bytes4", name: "expectedSelector", type: "bytes4" }], name: "invalidHookResponse", type: "error" },
  { inputs: [], name: "invalidLimitSqrtPrice", type: "error" },
  { inputs: [], name: "invalidNewCommunityFee", type: "error" },
  { inputs: [], name: "invalidNewTickSpacing", type: "error" },
  { inputs: [], name: "liquidityAdd", type: "error" },
  { inputs: [], name: "liquidityOverflow", type: "error" },
  { inputs: [], name: "liquiditySub", type: "error" },
  { inputs: [], name: "locked", type: "error" },
  { inputs: [], name: "notAllowed", type: "error" },
  { inputs: [], name: "notInitialized", type: "error" },
  { inputs: [], name: "pluginIsNotConnected", type: "error" },
  { inputs: [], name: "priceOutOfRange", type: "error" },
  { inputs: [], name: "tickInvalidLinks", type: "error" },
  { inputs: [], name: "tickIsNotInitialized", type: "error" },
  { inputs: [], name: "tickIsNotSpaced", type: "error" },
  { inputs: [], name: "tickOutOfRange", type: "error" },
  { inputs: [], name: "topTickAboveMAX", type: "error" },
  { inputs: [], name: "topTickLowerOrEqBottomTick", type: "error" },
  { inputs: [], name: "transferFailed", type: "error" },
  { inputs: [], name: "zeroAmountRequired", type: "error" },
  { inputs: [], name: "zeroLiquidityActual", type: "error" },
  { inputs: [], name: "zeroLiquidityDesired", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "int24", name: "bottomTick", type: "int24" },
      { indexed: true, internalType: "int24", name: "topTick", type: "int24" },
      { indexed: false, internalType: "uint128", name: "liquidityAmount", type: "uint128" },
      { indexed: false, internalType: "uint256", name: "amount0", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount1", type: "uint256" },
    ],
    name: "Burn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "address", name: "recipient", type: "address" },
      { indexed: true, internalType: "int24", name: "bottomTick", type: "int24" },
      { indexed: true, internalType: "int24", name: "topTick", type: "int24" },
      { indexed: false, internalType: "uint128", name: "amount0", type: "uint128" },
      { indexed: false, internalType: "uint128", name: "amount1", type: "uint128" },
    ],
    name: "Collect",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint16", name: "communityFeeNew", type: "uint16" }], name: "CommunityFee", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "newCommunityVault", type: "address" }], name: "CommunityVault", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint16", name: "fee", type: "uint16" }], name: "Fee", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "sender", type: "address" },
      { indexed: true, internalType: "address", name: "recipient", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount0", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount1", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "paid0", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "paid1", type: "uint256" },
    ],
    name: "Flash",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint160", name: "price", type: "uint160" },
      { indexed: false, internalType: "int24", name: "tick", type: "int24" },
    ],
    name: "Initialize",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "sender", type: "address" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "int24", name: "bottomTick", type: "int24" },
      { indexed: true, internalType: "int24", name: "topTick", type: "int24" },
      { indexed: false, internalType: "uint128", name: "liquidityAmount", type: "uint128" },
      { indexed: false, internalType: "uint256", name: "amount0", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount1", type: "uint256" },
    ],
    name: "Mint",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "newPluginAddress", type: "address" }], name: "Plugin", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint8", name: "newPluginConfig", type: "uint8" }], name: "PluginConfig", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "sender", type: "address" },
      { indexed: true, internalType: "address", name: "recipient", type: "address" },
      { indexed: false, internalType: "int256", name: "amount0", type: "int256" },
      { indexed: false, internalType: "int256", name: "amount1", type: "int256" },
      { indexed: false, internalType: "uint160", name: "price", type: "uint160" },
      { indexed: false, internalType: "uint128", name: "liquidity", type: "uint128" },
      { indexed: false, internalType: "int24", name: "tick", type: "int24" },
    ],
    name: "Swap",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "int24", name: "newTickSpacing", type: "int24" }], name: "TickSpacing", type: "event" },
  {
    inputs: [
      { internalType: "int24", name: "bottomTick", type: "int24" },
      { internalType: "int24", name: "topTick", type: "int24" },
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "burn",
    outputs: [
      { internalType: "uint256", name: "amount0", type: "uint256" },
      { internalType: "uint256", name: "amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "int24", name: "bottomTick", type: "int24" },
      { internalType: "int24", name: "topTick", type: "int24" },
      { internalType: "uint128", name: "amount0Requested", type: "uint128" },
      { internalType: "uint128", name: "amount1Requested", type: "uint128" },
    ],
    name: "collect",
    outputs: [
      { internalType: "uint128", name: "amount0", type: "uint128" },
      { internalType: "uint128", name: "amount1", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "communityFeeLastTimestamp", outputs: [{ internalType: "uint32", name: "", type: "uint32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "communityVault", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "factory", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "fee", outputs: [{ internalType: "uint16", name: "currentFee", type: "uint16" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount0", type: "uint256" },
      { internalType: "uint256", name: "amount1", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "flash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCommunityFeePending",
    outputs: [
      { internalType: "uint128", name: "", type: "uint128" },
      { internalType: "uint128", name: "", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      { internalType: "uint128", name: "", type: "uint128" },
      { internalType: "uint128", name: "", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "globalState",
    outputs: [
      { internalType: "uint160", name: "price", type: "uint160" },
      { internalType: "int24", name: "tick", type: "int24" },
      { internalType: "uint16", name: "lastFee", type: "uint16" },
      { internalType: "uint8", name: "pluginConfig", type: "uint8" },
      { internalType: "uint16", name: "communityFee", type: "uint16" },
      { internalType: "bool", name: "unlocked", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ internalType: "uint160", name: "initialPrice", type: "uint160" }], name: "initialize", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "isUnlocked", outputs: [{ internalType: "bool", name: "unlocked", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "liquidity", outputs: [{ internalType: "uint128", name: "", type: "uint128" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "maxLiquidityPerTick", outputs: [{ internalType: "uint128", name: "", type: "uint128" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "address", name: "leftoversRecipient", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "int24", name: "bottomTick", type: "int24" },
      { internalType: "int24", name: "topTick", type: "int24" },
      { internalType: "uint128", name: "liquidityDesired", type: "uint128" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "mint",
    outputs: [
      { internalType: "uint256", name: "amount0", type: "uint256" },
      { internalType: "uint256", name: "amount1", type: "uint256" },
      { internalType: "uint128", name: "liquidityActual", type: "uint128" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "nextTickGlobal", outputs: [{ internalType: "int24", name: "", type: "int24" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "plugin", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "positions",
    outputs: [
      { internalType: "uint256", name: "liquidity", type: "uint256" },
      { internalType: "uint256", name: "innerFeeGrowth0Token", type: "uint256" },
      { internalType: "uint256", name: "innerFeeGrowth1Token", type: "uint256" },
      { internalType: "uint128", name: "fees0", type: "uint128" },
      { internalType: "uint128", name: "fees1", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "prevTickGlobal", outputs: [{ internalType: "int24", name: "", type: "int24" }], stateMutability: "view", type: "function" },
  {
    inputs: [],
    name: "safelyGetStateOfAMM",
    outputs: [
      { internalType: "uint160", name: "sqrtPrice", type: "uint160" },
      { internalType: "int24", name: "tick", type: "int24" },
      { internalType: "uint16", name: "lastFee", type: "uint16" },
      { internalType: "uint8", name: "pluginConfig", type: "uint8" },
      { internalType: "uint128", name: "activeLiquidity", type: "uint128" },
      { internalType: "int24", name: "nextTick", type: "int24" },
      { internalType: "int24", name: "previousTick", type: "int24" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ internalType: "uint16", name: "newCommunityFee", type: "uint16" }], name: "setCommunityFee", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newCommunityVault", type: "address" }], name: "setCommunityVault", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint16", name: "newFee", type: "uint16" }], name: "setFee", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newPluginAddress", type: "address" }], name: "setPlugin", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint8", name: "newConfig", type: "uint8" }], name: "setPluginConfig", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "int24", name: "newTickSpacing", type: "int24" }], name: "setTickSpacing", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "bool", name: "zeroToOne", type: "bool" },
      { internalType: "int256", name: "amountRequired", type: "int256" },
      { internalType: "uint160", name: "limitSqrtPrice", type: "uint160" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "swap",
    outputs: [
      { internalType: "int256", name: "amount0", type: "int256" },
      { internalType: "int256", name: "amount1", type: "int256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "leftoversRecipient", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "bool", name: "zeroToOne", type: "bool" },
      { internalType: "int256", name: "amountToSell", type: "int256" },
      { internalType: "uint160", name: "limitSqrtPrice", type: "uint160" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "swapWithPaymentInAdvance",
    outputs: [
      { internalType: "int256", name: "amount0", type: "int256" },
      { internalType: "int256", name: "amount1", type: "int256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "tickSpacing", outputs: [{ internalType: "int24", name: "", type: "int24" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "int16", name: "", type: "int16" }], name: "tickTable", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "tickTreeRoot", outputs: [{ internalType: "uint32", name: "", type: "uint32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "int16", name: "", type: "int16" }], name: "tickTreeSecondLayer", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "int24", name: "", type: "int24" }],
    name: "ticks",
    outputs: [
      { internalType: "uint256", name: "liquidityTotal", type: "uint256" },
      { internalType: "int128", name: "liquidityDelta", type: "int128" },
      { internalType: "int24", name: "prevTick", type: "int24" },
      { internalType: "int24", name: "nextTick", type: "int24" },
      { internalType: "uint256", name: "outerFeeGrowth0Token", type: "uint256" },
      { internalType: "uint256", name: "outerFeeGrowth1Token", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "token0", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "token1", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalFeeGrowth0Token", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalFeeGrowth1Token", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
]  as const;

const ABI_AlgebraBasePluginV1 = [
  {
    inputs: [
      { internalType: "address", name: "_pool", type: "address" },
      { internalType: "address", name: "_factory", type: "address" },
      { internalType: "address", name: "_pluginFactory", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "targetIsTooOld", type: "error" },
  { inputs: [], name: "volatilityOracleAlreadyInitialized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: "uint16", name: "alpha1", type: "uint16" },
          { internalType: "uint16", name: "alpha2", type: "uint16" },
          { internalType: "uint32", name: "beta1", type: "uint32" },
          { internalType: "uint32", name: "beta2", type: "uint32" },
          { internalType: "uint16", name: "gamma1", type: "uint16" },
          { internalType: "uint16", name: "gamma2", type: "uint16" },
          { internalType: "uint16", name: "baseFee", type: "uint16" },
        ],
        indexed: false,
        internalType: "struct AlgebraFeeConfiguration",
        name: "feeConfig",
        type: "tuple",
      },
    ],
    name: "FeeConfiguration",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "newIncentive", type: "address" }], name: "Incentive", type: "event" },
  { inputs: [], name: "ALGEBRA_BASE_PLUGIN_MANAGER", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "afterFlash",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint160", name: "", type: "uint160" },
      { internalType: "int24", name: "tick", type: "int24" },
    ],
    name: "afterInitialize",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "int24", name: "", type: "int24" },
      { internalType: "int24", name: "", type: "int24" },
      { internalType: "int128", name: "", type: "int128" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "afterModifyPosition",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "bool", name: "zeroToOne", type: "bool" },
      { internalType: "int256", name: "", type: "int256" },
      { internalType: "uint160", name: "", type: "uint160" },
      { internalType: "int256", name: "", type: "int256" },
      { internalType: "int256", name: "", type: "int256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "afterSwap",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "beforeFlash",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint160", name: "", type: "uint160" },
    ],
    name: "beforeInitialize",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "int24", name: "", type: "int24" },
      { internalType: "int24", name: "", type: "int24" },
      { internalType: "int128", name: "", type: "int128" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "beforeModifyPosition",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "int256", name: "", type: "int256" },
      { internalType: "uint160", name: "", type: "uint160" },
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "beforeSwap",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint16", name: "alpha1", type: "uint16" },
          { internalType: "uint16", name: "alpha2", type: "uint16" },
          { internalType: "uint32", name: "beta1", type: "uint32" },
          { internalType: "uint32", name: "beta2", type: "uint32" },
          { internalType: "uint16", name: "gamma1", type: "uint16" },
          { internalType: "uint16", name: "gamma2", type: "uint16" },
          { internalType: "uint16", name: "baseFee", type: "uint16" },
        ],
        internalType: "struct AlgebraFeeConfiguration",
        name: "_config",
        type: "tuple",
      },
    ],
    name: "changeFeeConfiguration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "defaultPluginConfig", outputs: [{ internalType: "uint8", name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  {
    inputs: [],
    name: "feeConfig",
    outputs: [
      { internalType: "uint16", name: "alpha1", type: "uint16" },
      { internalType: "uint16", name: "alpha2", type: "uint16" },
      { internalType: "uint32", name: "beta1", type: "uint32" },
      { internalType: "uint32", name: "beta2", type: "uint32" },
      { internalType: "uint16", name: "gamma1", type: "uint16" },
      { internalType: "uint16", name: "gamma2", type: "uint16" },
      { internalType: "uint16", name: "baseFee", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "getCurrentFee", outputs: [{ internalType: "uint16", name: "fee", type: "uint16" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "uint32", name: "secondsAgo", type: "uint32" }],
    name: "getSingleTimepoint",
    outputs: [
      { internalType: "int56", name: "tickCumulative", type: "int56" },
      { internalType: "uint88", name: "volatilityCumulative", type: "uint88" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32[]", name: "secondsAgos", type: "uint32[]" }],
    name: "getTimepoints",
    outputs: [
      { internalType: "int56[]", name: "tickCumulatives", type: "int56[]" },
      { internalType: "uint88[]", name: "volatilityCumulatives", type: "uint88[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "incentive", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "initialize", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "targetIncentive", type: "address" }], name: "isIncentiveConnected", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "isInitialized", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "lastTimepointTimestamp", outputs: [{ internalType: "uint32", name: "", type: "uint32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "pool", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "uint16", name: "startIndex", type: "uint16" },
      { internalType: "uint16", name: "amount", type: "uint16" },
    ],
    name: "prepayTimepointsStorageSlots",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ internalType: "address", name: "newIncentive", type: "address" }], name: "setIncentive", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "timepointIndex", outputs: [{ internalType: "uint16", name: "", type: "uint16" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "timepoints",
    outputs: [
      { internalType: "bool", name: "initialized", type: "bool" },
      { internalType: "uint32", name: "blockTimestamp", type: "uint32" },
      { internalType: "int56", name: "tickCumulative", type: "int56" },
      { internalType: "uint88", name: "volatilityCumulative", type: "uint88" },
      { internalType: "int24", name: "tick", type: "int24" },
      { internalType: "int24", name: "averageTick", type: "int24" },
      { internalType: "uint16", name: "windowStartIndex", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
