

PRIVATEKEY = [`0x${"INSERT_YOUR_PVKEY"}`]

APIKEY_POLYGONSCAN = "INSERT_YOUR_APY_KEY"
APIKEY_BLOCKSCOUT_ZETACHAIN = "INSERT_YOUR_APY_KEY"

module.exports = {PRIVATEKEY, APIKEY_POLYGONSCAN, APIKEY_BLOCKSCOUT_ZETACHAIN }
